export interface SocialPlatformConfig {
  id: string
  name: string
  color: string
  bgColor: string
  maxChars: number
  hasMedia: boolean
  hasPoll: boolean
  hasCarousel: boolean
  iconName: string
}

export const SOCIAL_PLATFORMS: Record<string, SocialPlatformConfig> = {
  INSTAGRAM: {
    id: "INSTAGRAM",
    name: "Instagram",
    color: "#E1306C",
    bgColor: "bg-gradient-to-r from-purple-500 via-pink-500 to-amber-500",
    maxChars: 2200,
    hasMedia: true,
    hasPoll: true,
    hasCarousel: true,
    iconName: "Instagram",
  },
  FACEBOOK: {
    id: "FACEBOOK",
    name: "Facebook Page",
    color: "#1877F2",
    bgColor: "bg-blue-600",
    maxChars: 63206,
    hasMedia: true,
    hasPoll: true,
    hasCarousel: true,
    iconName: "Facebook",
  },
  LINKEDIN: {
    id: "LINKEDIN",
    name: "LinkedIn",
    color: "#0A66C2",
    bgColor: "bg-sky-700",
    maxChars: 3000,
    hasMedia: true,
    hasPoll: true,
    hasCarousel: true,
    iconName: "Linkedin",
  },
  TWITTER: {
    id: "TWITTER",
    name: "Twitter / X",
    color: "#000000",
    bgColor: "bg-slate-900",
    maxChars: 280,
    hasMedia: true,
    hasPoll: true,
    hasCarousel: true,
    iconName: "Twitter",
  },
  THREADS: {
    id: "THREADS",
    name: "Threads",
    color: "#000000",
    bgColor: "bg-zinc-800",
    maxChars: 500,
    hasMedia: true,
    hasPoll: false,
    hasCarousel: true,
    iconName: "AtSign",
  },
  PINTEREST: {
    id: "PINTEREST",
    name: "Pinterest",
    color: "#E60023",
    bgColor: "bg-red-600",
    maxChars: 500,
    hasMedia: true,
    hasPoll: false,
    hasCarousel: false,
    iconName: "Pin",
  },
  TIKTOK: {
    id: "TIKTOK",
    name: "TikTok",
    color: "#00F2FE",
    bgColor: "bg-zinc-900",
    maxChars: 2200,
    hasMedia: true,
    hasPoll: false,
    hasCarousel: false,
    iconName: "Video",
  },
  YOUTUBE: {
    id: "YOUTUBE",
    name: "YouTube Shorts",
    color: "#FF0000",
    bgColor: "bg-red-600",
    maxChars: 5000,
    hasMedia: true,
    hasPoll: false,
    hasCarousel: false,
    iconName: "Youtube",
  },
  GOOGLE_BUSINESS: {
    id: "GOOGLE_BUSINESS",
    name: "Google Business",
    color: "#4285F4",
    bgColor: "bg-blue-500",
    maxChars: 1500,
    hasMedia: true,
    hasPoll: false,
    hasCarousel: false,
    iconName: "Store",
  },
  MASTODON: {
    id: "MASTODON",
    name: "Mastodon",
    color: "#6364FF",
    bgColor: "bg-indigo-600",
    maxChars: 500,
    hasMedia: true,
    hasPoll: true,
    hasCarousel: false,
    iconName: "Globe",
  },
}

export const AI_MODELS = [
  { id: "gpt-4o", name: "OpenAI GPT-4o", provider: "OpenAI", speed: "Fast", quality: "Ultra" },
  { id: "claude-3.5-sonnet", name: "Claude 3.5 Sonnet", provider: "Anthropic", speed: "Super Fast", quality: "Elite" },
  { id: "gemini-1.5-pro", name: "Google Gemini 1.5 Pro", provider: "Google DeepMind", speed: "Instant", quality: "Ultra" },
  { id: "deepseek-v3", name: "DeepSeek V3", provider: "DeepSeek", speed: "Ultra Fast", quality: "High" },
]

export const SUBSCRIPTION_PLANS = [
  {
    id: "FREE",
    name: "Free Trial",
    price: "$0",
    period: "forever",
    accountsLimit: 3,
    postsPerMonth: 30,
    aiCredits: 50,
    members: 1,
    features: ["Basic Scheduling", "3 Connected Accounts", "50 AI Credits/mo", "Community Support"],
  },
  {
    id: "STARTER",
    name: "Starter",
    price: "$29",
    period: "per month",
    accountsLimit: 10,
    postsPerMonth: 300,
    aiCredits: 1000,
    members: 3,
    popular: true,
    features: ["10 Connected Accounts", "1,000 AI Credits", "3 Team Seats", "Unified Inbox", "Basic Analytics"],
  },
  {
    id: "PROFESSIONAL",
    name: "Professional",
    price: "$79",
    period: "per month",
    accountsLimit: 25,
    postsPerMonth: 2000,
    aiCredits: 5000,
    members: 10,
    features: ["25 Connected Accounts", "5,000 AI Credits", "10 Team Seats", "AI Auto-Replies", "Advanced Analytics & CSV Export", "Brand Kit & Watermarking"],
  },
  {
    id: "AGENCY",
    name: "Agency",
    price: "$199",
    period: "per month",
    accountsLimit: 100,
    postsPerMonth: 10000,
    aiCredits: 20000,
    members: 35,
    features: ["100 Connected Accounts", "20,000 AI Credits", "Multi-Org Management", "White-label PDF Reports", "Priority AI Queue", "Dedicated Support"],
  },
  {
    id: "ENTERPRISE",
    name: "Enterprise",
    price: "Custom",
    period: "annual billing",
    accountsLimit: 999,
    postsPerMonth: 99999,
    aiCredits: 100000,
    members: 100,
    features: ["Unlimited Accounts", "Custom AI Fine-tuning", "SAML SSO & Audit Logs", "Custom SLAs", "Dedicated Account Manager"],
  },
]
